name: PlatformIO CI

on: [push]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install PIO Core
        run: pip install --upgrade platformio

      - name: Build examples
        run: bash scripts/ci.sh

      - name: Lint project
        run: bash scripts/lint.sh
